kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: cloudtask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: backend-image
        image: 288096932508.dkr.ecr.ap-south-1.amazonaws.com/todo-repo:backend-10
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://mongo-service:27017
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5