resources:
  - backend/deployment.yml
  - backend/service.yml

  - frontend/deployment.yml
  - frontend/service.yml

  - mongo/deployment.yml
  - mongo/service.yml

  - ingress.yml
  - namespace.yml
  - pv.yml
  - pvc.yml
  - secret.yml
  - hpa.yml